---

- name: NVM | main | Install Required Packages
  become: "{{ nvm_apt_become }}"
  apt:
    update_cache: yes
    state: present
    pkg: "{{ required_packages }}"

- include: nvm.yml

- include: node.yml

- include: pkgs.yml
  when: "{{ nvm_npm_pkgs | length }} > 0"

# needed in order to preserve idempotency due to globally installed packages
- include: permission.yml
