---

- name: NVM | nvm | get stats on nvm
  stat: path="{{ nvm_dest }}"
  register: nvm_stat

- name: NVM | nvm | download nvm script
  get_url:
    dest: "{{ nvm_dest }}"
    url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh

- name: NVM | nvm | install nvm
  shell: "NVM_DIR=\"{{ nvm_dest }}\" NODE_VERSION=\"{{ nvm_node_version }}\" source {{ nvm_dest }}/install.sh"
  args:
    executable: /bin/bash
