---

- name: NVM | pkgs | install npm module(s)
  shell: "source {{ nvm_dest }}/nvm.sh && nvm use {{ nvm_node_version }} && npm install -g {{ item.pkg }}@{{ item.version }}"
  with_items: "{{nvm_npm_pkgs}}"
  args:
    executable: /bin/bash
